# Operaciones avanzadas con data frames

Crea un programa llamado ParquesEolicosProvincia.py que utilice el archivo CSV que se te proporciona sobre parques eólicos de la comunidad de Castilla y León.

In [22]:
import pandas as pd

df = pd.read_csv("parques_eolicos.csv", sep=";")
df

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
0,225.0,Aerogenerador Experimental I+D G-87,Lubián,ZA,2000,GAMESA,1,2000
1,226.0,Aerogenerador Experimental I+D G-90,Lubián,ZA,2000,GAMESA,1,2000
2,162.0,Ágreda,Agreda,SO,18000,ACCIONA,12,1500
3,153.0,ALBA DE TORMES,Alba de Tormes,SA,4500,MTORRES,3,1500
4,108.0,Alconada,Ampudia,PA,4500,ACCIONA,3,1500
...,...,...,...,...,...,...,...,...
245,161.0,Villacastín,Villacastín,SG,14520,GAMESA,22,660
246,250.0,Villalazán,"Toro, Villalazán y Madridanos",ZA,4980,GAMESA,6,830
247,90.0,Villamiel,Villamiel de la Sierra y Villoruebo,BU,17850,GAMESA,21,850
248,91.0,Villoruebo,Villoruebo y Palazuelos de la Sierra,BU,16150,GAMESA,19,850
249,203.0,Zorraquín,Golmayo y Villaciervos,SO,12000,GAMESA,6,2000

Nos interesa quedarnos con los parques de la provincia de Zamora que tengas más de 10 aerogeneradores.

In [23]:
condicion = (df['provincia'] == 'ZA') & (df['aerogeneradores'] > 10)
df_parques_zamora = df[condicion]
df_parques_zamora

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
11,227.0,Ampliación a El Aguallal,Lubián y Pías,ZA,24950,GAMESA,27,850
12,229.0,Ampliación a La Gamoneda,Lubián y Hermisende,ZA,29750,GAMESA,35,850
15,228.0,AMPLIACIÓN DEL HIERRO,"Losacio, Losacino, Carbajales de Alba y Olmill...",ZA,43200,GAMESA,12,3600
62,233.0,El Aguallal,Lubián y Pías,ZA,11880,GAMESA,18,660
74,234.0,El Hierro,Olmillos de Castro y Santa Eufemia del Barco,ZA,22400,ECOTECNIA,14,1600
103,235.0,Hedroso-Aciberos,Lubián,ZA,31450,GAMESA,37,850
117,236.0,La Gamoneda,Lubián y Hermisende,ZA,19800,GAMESA,30,660
134,239.0,Labradas Fusionado,"Villaferrueña, Arrabalde, Alcubilla de Nogales...",ZA,36550,GAMESA,43,850
154,240.0,Lubián,Lubián,ZA,50000,GAMESA,25,2000
161,241.0,Montamarta,"Montamarta, Palacios del Pan y Andavías",ZA,22400,ECOTECNIA,14,1600
169,242.0,Nerea,Requejo y Pedralba de la Pradería,ZA,39750,ECOTECNIA,53,750
173,243.0,Padornelo,Lubián,ZA,31450,GAMESA,37,850
186,244.0,Peñarroldana,Santa Eufemia del Barco,ZA,35200,ECOTECNIA,22,1600
205,245.0,San Ciprián,Lubián y Hermisende,ZA,17850,GAMESA,21,850
212,224.0,Sierra de las Carbas,Ferreruela,ZA,40000,GAMESA,20,2000
242,249.0,Valmediano,Tábara y Faramontanos de Tábara,ZA,34000,GAMESA,40,850

Muestra el listado resultante ordenado por número de aerogeneradores.

In [24]:
df_parques_zamora = df_parques_zamora.sort_values(by='aerogeneradores', ascending=True)
df_parques_zamora

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
15,228.0,AMPLIACIÓN DEL HIERRO,"Losacio, Losacino, Carbajales de Alba y Olmill...",ZA,43200,GAMESA,12,3600
74,234.0,El Hierro,Olmillos de Castro y Santa Eufemia del Barco,ZA,22400,ECOTECNIA,14,1600
161,241.0,Montamarta,"Montamarta, Palacios del Pan y Andavías",ZA,22400,ECOTECNIA,14,1600
62,233.0,El Aguallal,Lubián y Pías,ZA,11880,GAMESA,18,660
212,224.0,Sierra de las Carbas,Ferreruela,ZA,40000,GAMESA,20,2000
205,245.0,San Ciprián,Lubián y Hermisende,ZA,17850,GAMESA,21,850
186,244.0,Peñarroldana,Santa Eufemia del Barco,ZA,35200,ECOTECNIA,22,1600
154,240.0,Lubián,Lubián,ZA,50000,GAMESA,25,2000
11,227.0,Ampliación a El Aguallal,Lubián y Pías,ZA,24950,GAMESA,27,850
117,236.0,La Gamoneda,Lubián y Hermisende,ZA,19800,GAMESA,30,660
12,229.0,Ampliación a La Gamoneda,Lubián y Hermisende,ZA,29750,GAMESA,35,850
103,235.0,Hedroso-Aciberos,Lubián,ZA,31450,GAMESA,37,850
173,243.0,Padornelo,Lubián,ZA,31450,GAMESA,37,850
242,249.0,Valmediano,Tábara y Faramontanos de Tábara,ZA,34000,GAMESA,40,850
134,239.0,Labradas Fusionado,"Villaferrueña, Arrabalde, Alcubilla de Nogales...",ZA,36550,GAMESA,43,850
169,242.0,Nerea,Requejo y Pedralba de la Pradería,ZA,39750,ECOTECNIA,53,750

In [25]:
df_parques_zamora = df_parques_zamora.reset_index(drop=True)
df_parques_zamora

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
0,228.0,AMPLIACIÓN DEL HIERRO,"Losacio, Losacino, Carbajales de Alba y Olmill...",ZA,43200,GAMESA,12,3600
1,234.0,El Hierro,Olmillos de Castro y Santa Eufemia del Barco,ZA,22400,ECOTECNIA,14,1600
2,241.0,Montamarta,"Montamarta, Palacios del Pan y Andavías",ZA,22400,ECOTECNIA,14,1600
3,233.0,El Aguallal,Lubián y Pías,ZA,11880,GAMESA,18,660
4,224.0,Sierra de las Carbas,Ferreruela,ZA,40000,GAMESA,20,2000
5,245.0,San Ciprián,Lubián y Hermisende,ZA,17850,GAMESA,21,850
6,244.0,Peñarroldana,Santa Eufemia del Barco,ZA,35200,ECOTECNIA,22,1600
7,240.0,Lubián,Lubián,ZA,50000,GAMESA,25,2000
8,227.0,Ampliación a El Aguallal,Lubián y Pías,ZA,24950,GAMESA,27,850
9,236.0,La Gamoneda,Lubián y Hermisende,ZA,19800,GAMESA,30,660
10,229.0,Ampliación a La Gamoneda,Lubián y Hermisende,ZA,29750,GAMESA,35,850
11,235.0,Hedroso-Aciberos,Lubián,ZA,31450,GAMESA,37,850
12,243.0,Padornelo,Lubián,ZA,31450,GAMESA,37,850
13,249.0,Valmediano,Tábara y Faramontanos de Tábara,ZA,34000,GAMESA,40,850
14,239.0,Labradas Fusionado,"Villaferrueña, Arrabalde, Alcubilla de Nogales...",ZA,36550,GAMESA,43,850
15,242.0,Nerea,Requejo y Pedralba de la Pradería,ZA,39750,ECOTECNIA,53,750