# Operaciones básicas con data frames

Crea un programa llamado VentasEmpresas.py que cree un data frame con los datos de la siguiente tabla y los muestre por pantalla (puedes emplear tabulate para ello)

In [37]:
import pandas as pd

datos_array = [
  ["Enero", 20600, 17900],
  ["Abril", 22500, 18500],
  ["Julio", 15400, 17600],
  ["Octubre", 21100, 18200]
]
df_datos_array = pd.DataFrame(datos_array, columns=["Mes", "Ventas", "Gastos"])

print(df_datos_array)

       Mes  Ventas  Gastos
0    Enero   20600   17900
1    Abril   22500   18500
2    Julio   15400   17600
3  Octubre   21100   18200

In [38]:
from tabulate import tabulate

print(tabulate(df_datos_array, headers="keys", tablefmt="pretty"))

+---+---------+--------+--------+
|   |   Mes   | Ventas | Gastos |
+---+---------+--------+--------+
| 0 |  Enero  | 20600  | 17900  |
| 1 |  Abril  | 22500  | 18500  |
| 2 |  Julio  | 15400  | 17600  |
| 3 | Octubre | 21100  | 18200  |
+---+---------+--------+--------+

In [39]:
datos_dict = {}
datos_dict["meses"] = ["Enero", "Abril", "Julio", "Octubre"]
datos_dict["ventas"] = [20600, 22500, 15400, 21100]
datos_dict["gastos"] = [17900, 18500, 17600, 18200]
df_datos_dict = pd.DataFrame(datos_dict)

print(df_datos_dict)

     meses  ventas  gastos
0    Enero   20600   17900
1    Abril   22500   18500
2    Julio   15400   17600
3  Octubre   21100   18200

In [40]:
print(tabulate(datos_dict, headers="keys", tablefmt="pretty"))

+---------+--------+--------+
|  meses  | ventas | gastos |
+---------+--------+--------+
|  Enero  | 20600  | 17900  |
|  Abril  | 22500  | 18500  |
|  Julio  | 15400  | 17600  |
| Octubre | 21100  | 18200  |
+---------+--------+--------+

Prueba a usar otras de las funciones y propiedades vistas y comprueba cómo funcionan.

In [41]:
df_datos_dict.head(2)

   meses  ventas  gastos
0  Enero   20600   17900
1  Abril   22500   18500

In [42]:
df_datos_dict.tail(2)

     meses  ventas  gastos
2    Julio   15400   17600
3  Octubre   21100   18200

In [43]:
print(df_datos_dict.describe())

             ventas        gastos
count      4.000000      4.000000
mean   19900.000000  18050.000000
std     3105.908348    387.298335
min    15400.000000  17600.000000
25%    19300.000000  17825.000000
50%    20850.000000  18050.000000
75%    21450.000000  18275.000000
max    22500.000000  18500.000000

In [44]:
df_datos_array.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Mes     4 non-null      object
 1   Ventas  4 non-null      int64
 2   Gastos  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [45]:
dimensiones = df_datos_dict.shape
filas = dimensiones[0]
columnas = dimensiones[1]

print(f"Dimensiones: {dimensiones}")
print(f"Filas: {filas}")
print(f"Columnas: {columnas}")

Dimensiones: (4, 3)
Filas: 4
Columnas: 3

In [46]:
print(f"Size: {df_datos_dict.size}")

Size: 12

In [47]:
print(f"Data types:\n{df_datos_dict.dtypes}")

Data types:
meses     object
ventas     int64
gastos     int64
dtype: object