# Ejercicio propuesto

- Crea un programa llamado LimpiarCSV.py y, partiendo del fichero CSV que se te proporcionará:
  - Homogeiniza la columna "nombre" para que todos los nombres estén capitalizados.
  - Detecta y elimina las filas duplicadas.
  - Limpia espacios sobrantes en la columna "provincia".

In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv("archivo.csv", sep=',')
df

          nombre  edad                          email   telefono    provincia
0   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344     Alicante
1     Juan pérez    70                juanp@gmail.com  699887766     Toledo
2  elena sánchez    33            e.sanchez@gmail.com  612345678     Alicante
3  Alicia Molina    54        alicia.molina@gmail.com  655443322     Valencia
4   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344     Alicante
5  Alicia Molina    54        alicia.molina@gmail.com  655443322     Valencia

In [62]:
# Homogeneizar nombrees
df['nombre'] = df['nombre'].str.title()
df

          nombre  edad                          email   telefono    provincia
0   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344     Alicante
1     Juan Pérez    70                juanp@gmail.com  699887766     Toledo
2  Elena Sánchez    33            e.sanchez@gmail.com  612345678     Alicante
3  Alicia Molina    54        alicia.molina@gmail.com  655443322     Valencia
4   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344     Alicante
5  Alicia Molina    54        alicia.molina@gmail.com  655443322     Valencia

In [63]:
# Detectar y eliminar filas duplicadas
print(f"Datos duplicados: {df.duplicated()}")
df = df.drop_duplicates()
df

Datos duplicados: 0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

          nombre  edad                          email   telefono    provincia
0   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344     Alicante
1     Juan Pérez    70                juanp@gmail.com  699887766     Toledo
2  Elena Sánchez    33            e.sanchez@gmail.com  612345678     Alicante
3  Alicia Molina    54        alicia.molina@gmail.com  655443322     Valencia

In [64]:
# Eliminar espacios de provincias
# warning: df.loc['provincia'] = df['provincia'].str.strip()
df.loc[:, 'provincia'] = df['provincia'].str.strip()
df

          nombre  edad                          email   telefono provincia
0   Nacho Iborra    44  nachoiborra@iessanvicente.com  611223344  Alicante
1     Juan Pérez    70                juanp@gmail.com  699887766    Toledo
2  Elena Sánchez    33            e.sanchez@gmail.com  612345678  Alicante
3  Alicia Molina    54        alicia.molina@gmail.com  655443322  Valencia