# Ejercicio propuesto

- Crea un programa llamado CalendarioLiga.py que utilice el dataset que se te proporcionará sobre la liga de fútbol española en la temporada 2022-23.
- Se pide que indexes el dataset por la fecha de los partidos (campo Date) y listes los partidos del mes de octubre.

In [19]:
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
df_liga = pd.read_csv("liga_22_23.csv", sep=',')
df_liga.head()

    Season        Date    HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR
0  2022-23  12-08-2022     Osasuna     Sevilla     2     1   H     1     1   D
1  2022-23  13-08-2022       Celta     Espanol     2     2   D     1     0   H
2  2022-23  13-08-2022  Valladolid  Villarreal     0     3   A     0     0   D
3  2022-23  13-08-2022   Barcelona   Vallecano     0     0   D     0     0   D
4  2022-23  14-08-2022       Cadiz    Sociedad     0     1   A     0     1   A

In [21]:
df_liga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Season    380 non-null    object
 1   Date      380 non-null    object
 2   HomeTeam  380 non-null    object
 3   AwayTeam  380 non-null    object
 4   FTHG      380 non-null    int64
 5   FTAG      380 non-null    int64
 6   FTR       380 non-null    object
 7   HTHG      380 non-null    int64
 8   HTAG      380 non-null    int64
 9   HTR       380 non-null    object
dtypes: int64(4), object(6)
memory usage: 29.8+ KB

In [22]:
df_liga['Date'] = pd.to_datetime(df_liga['Date'], format='%d-%m-%Y')
df_liga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Season    380 non-null    object
 1   Date      380 non-null    datetime64[ns]
 2   HomeTeam  380 non-null    object
 3   AwayTeam  380 non-null    object
 4   FTHG      380 non-null    int64
 5   FTAG      380 non-null    int64
 6   FTR       380 non-null    object
 7   HTHG      380 non-null    int64
 8   HTAG      380 non-null    int64
 9   HTR       380 non-null    object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 29.8+ KB

In [23]:
df_liga = df_liga.set_index('Date').sort_index()
df_liga.head()

             Season    HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR
Date
2022-08-12  2022-23     Osasuna     Sevilla     2     1   H     1     1   D
2022-08-13  2022-23       Celta     Espanol     2     2   D     1     0   H
2022-08-13  2022-23  Valladolid  Villarreal     0     3   A     0     0   D
2022-08-13  2022-23   Barcelona   Vallecano     0     0   D     0     0   D
2022-08-14  2022-23       Cadiz    Sociedad     0     1   A     0     1   A

In [24]:
octubre_22 = df_liga.loc['2022-10']
print(f"Cantidad partidos (filas) en octubre: {octubre_22.shape[0]}")

Cantidad partidos (filas) en octubre: 59

In [25]:
print(octubre_22)

             Season     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR
Date
2022-10-01  2022-23        Cadiz   Villarreal     0     0   D     0     0   D
2022-10-01  2022-23       Getafe   Valladolid     2     3   A     2     2   D
2022-10-01  2022-23      Sevilla   Ath Madrid     0     2   A     0     1   A
2022-10-01  2022-23     Mallorca    Barcelona     0     1   A     0     1   A
2022-10-02  2022-23      Espanol     Valencia     2     2   D     0     0   D
2022-10-02  2022-23        Celta        Betis     1     0   H     1     0   H
2022-10-02  2022-23       Girona     Sociedad     3     5   A     2     2   D
2022-10-02  2022-23  Real Madrid      Osasuna     1     1   D     1     0   H
2022-10-03  2022-23    Vallecano        Elche     2     1   H     1     1   D
2022-10-07  2022-23      Osasuna     Valencia     1     2   A     0     1   A
2022-10-08  2022-23      Almeria    Vallecano     3     1   H     3     0   H
2022-10-08  2022-23   Ath Madrid       Girona     2     1   H     1     0   H
2022-10-08  2022-23      Sevilla   Ath Bilbao     1     1   D     1     0   H
2022-10-08  2022-23       Getafe  Real Madrid     0     1   A     0     1   A
2022-10-09  2022-23   Valladolid        Betis     0     0   D     0     0   D
2022-10-09  2022-23        Cadiz      Espanol     2     2   D     1     0   H
2022-10-09  2022-23     Sociedad   Villarreal     1     0   H     1     0   H
2022-10-09  2022-23    Barcelona        Celta     1     0   H     1     0   H
2022-10-10  2022-23        Elche     Mallorca     1     1   D     1     0   H
2022-10-14  2022-23    Vallecano       Getafe     0     0   D     0     0   D
2022-10-15  2022-23       Girona        Cadiz     1     1   D     0     0   D
2022-10-15  2022-23     Valencia        Elche     2     2   D     2     1   H
2022-10-15  2022-23     Mallorca      Sevilla     0     1   A     0     0   D
2022-10-15  2022-23   Ath Bilbao   Ath Madrid     0     1   A     0     0   D
2022-10-16  2022-23        Celta     Sociedad     1     2   A     1     1   D
2022-10-16  2022-23  Real Madrid    Barcelona     3     1   H     2     0   H
2022-10-16  2022-23      Espanol   Valladolid     1     0   H     0     0   D
2022-10-16  2022-23        Betis      Almeria     3     1   H     1     0   H
2022-10-17  2022-23   Villarreal      Osasuna     2     0   H     1     0   H
2022-10-18  2022-23      Sevilla     Valencia     1     1   D     0     1   A
2022-10-18  2022-23       Getafe   Ath Bilbao     2     2   D     1     1   D
2022-10-18  2022-23   Ath Madrid    Vallecano     1     1   D     1     0   H
2022-10-19  2022-23        Cadiz        Betis     0     0   D     0     0   D
2022-10-19  2022-23   Valladolid        Celta     4     1   H     1     1   D
2022-10-19  2022-23     Sociedad     Mallorca     1     0   H     1     0   H
2022-10-19  2022-23        Elche  Real Madrid     0     3   A     0     1   A
2022-10-20  2022-23      Almeria       Girona     3     2   H     3     0   H
2022-10-20  2022-23      Osasuna      Espanol     1     0   H     0     0   D
2022-10-20  2022-23    Barcelona   Villarreal     3     0   H     3     0   H
2022-10-22  2022-23    Vallecano        Cadiz     5     1   H     2     0   H
2022-10-22  2022-23   Valladolid     Sociedad     1     0   H     1     0   H
2022-10-22  2022-23     Valencia     Mallorca     1     2   A     0     0   D
2022-10-22  2022-23  Real Madrid      Sevilla     3     1   H     1     0   H
2022-10-23  2022-23      Espanol        Elche     2     2   D     1     1   D
2022-10-23  2022-23        Betis   Ath Madrid     1     2   A     0     0   D
2022-10-23  2022-23       Girona      Osasuna     1     1   D     1     1   D
2022-10-23  2022-23   Villarreal      Almeria     2     1   H     0     1   A
2022-10-23  2022-23    Barcelona   Ath Bilbao     4     0   H     3     0   H
2022-10-24  2022-23        Celta       Getafe     1     1   D     0     1   A
2022-10-28  2022-23     Mallorca      Espanol     1     1   D     0     0   D
2022-10-29  2022-23      Almeria        Celta     3     1   H     0     1   A
2022-10-29  2022-23        Cadiz   Ath Madrid     3     2   H     1     0   H
2022-10-29  2022-23      Sevilla    Vallecano     0     1   A     0     0   D
2022-10-29  2022-23     Valencia    Barcelona     0     1   A     0     0   D
2022-10-30  2022-23      Osasuna   Valladolid     2     0   H     2     0   H
2022-10-30  2022-23  Real Madrid       Girona     1     1   D     0     0   D
2022-10-30  2022-23   Ath Bilbao   Villarreal     1     0   H     0     0   D
2022-10-30  2022-23     Sociedad        Betis     0     2   A     0     0   D
2022-10-31  2022-23        Elche       Getafe     0     1   A     0     0   D