# Ejercicio propuesto

- Crea un programa llamado ProvinciasOneHot.py que utilice el CSV que se te proporciona sobre parques eólicos en Castilla y León, y codifica los valores de la columna "provincia" usando "one hot encoding", y eliminando la columna original. Muestra luego las 5 primeras filas para ver el resultado.

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("parques_eolicos.csv", sep=';')
df.head()

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
0,225.0,Aerogenerador Experimental I+D G-87,Lubián,ZA,2000,GAMESA,1,2000
1,226.0,Aerogenerador Experimental I+D G-90,Lubián,ZA,2000,GAMESA,1,2000
2,162.0,Ágreda,Agreda,SO,18000,ACCIONA,12,1500
3,153.0,ALBA DE TORMES,Alba de Tormes,SA,4500,MTORRES,3,1500
4,108.0,Alconada,Ampudia,PA,4500,ACCIONA,3,1500

In [13]:
df = pd.get_dummies(
    df,
    columns=['provincia'],
    prefix='prov',
    dtype=int) # Sin dtype -> True/False en lugar de 1/0
df.head()

,num,nombre,municipio,potencia,tecnologia,aerogeneradores,potencia_unitaria,prov_AV,prov_BU,prov_LE,prov_PA,prov_SA,prov_SG,prov_SO,prov_VA,prov_ZA
0,225.0,Aerogenerador Experimental I+D G-87,Lubián,2000,GAMESA,1,2000,0,0,0,0,0,0,0,0,1
1,226.0,Aerogenerador Experimental I+D G-90,Lubián,2000,GAMESA,1,2000,0,0,0,0,0,0,0,0,1
2,162.0,Ágreda,Agreda,18000,ACCIONA,12,1500,0,0,0,0,0,0,1,0,0
3,153.0,ALBA DE TORMES,Alba de Tormes,4500,MTORRES,3,1500,0,0,0,0,1,0,0,0,0
4,108.0,Alconada,Ampudia,4500,ACCIONA,3,1500,0,0,0,1,0,0,0,0,0