# Ejercicio propuesto

- Crea un programa llamado EscaladoPotencia.py que utilice el archivo CSV que se te proporcionará sobre parques eólicos en Castilla y León y crea una nueva columna llamada `potencia_unitaria_norm` que normalice los valores de la columna `potencia_unitaria` entre 0 y 1.

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("parques_eolicos.csv", sep=';')
df.head()

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria
0,225.0,Aerogenerador Experimental I+D G-87,Lubián,ZA,2000,GAMESA,1,2000
1,226.0,Aerogenerador Experimental I+D G-90,Lubián,ZA,2000,GAMESA,1,2000
2,162.0,Ágreda,Agreda,SO,18000,ACCIONA,12,1500
3,153.0,ALBA DE TORMES,Alba de Tormes,SA,4500,MTORRES,3,1500
4,108.0,Alconada,Ampudia,PA,4500,ACCIONA,3,1500

In [24]:
potencia_unitaria_min = df['potencia_unitaria'].min()
potencia_unitaria_max = df['potencia_unitaria'].max()

print(f"Potencia unitaria mímina: {potencia_unitaria_min}")
print(f"Potencia unitaria máxima: {potencia_unitaria_max}")

Potencia unitaria mímina: 150
Potencia unitaria máxima: 4500

In [26]:
df['potencia_unitaria_norm'] = (df['potencia_unitaria'] - potencia_unitaria_min) / \
 (potencia_unitaria_max - potencia_unitaria_min)

df

,num,nombre,municipio,provincia,potencia,tecnologia,aerogeneradores,potencia_unitaria,potencia_unitaria_norm
0,225.0,Aerogenerador Experimental I+D G-87,Lubián,ZA,2000,GAMESA,1,2000,0.425287
1,226.0,Aerogenerador Experimental I+D G-90,Lubián,ZA,2000,GAMESA,1,2000,0.425287
2,162.0,Ágreda,Agreda,SO,18000,ACCIONA,12,1500,0.310345
3,153.0,ALBA DE TORMES,Alba de Tormes,SA,4500,MTORRES,3,1500,0.310345
4,108.0,Alconada,Ampudia,PA,4500,ACCIONA,3,1500,0.310345
...,...,...,...,...,...,...,...,...,...
245,161.0,Villacastín,Villacastín,SG,14520,GAMESA,22,660,0.117241
246,250.0,Villalazán,"Toro, Villalazán y Madridanos",ZA,4980,GAMESA,6,830,0.156322
247,90.0,Villamiel,Villamiel de la Sierra y Villoruebo,BU,17850,GAMESA,21,850,0.160920
248,91.0,Villoruebo,Villoruebo y Palazuelos de la Sierra,BU,16150,GAMESA,19,850,0.160920
249,203.0,Zorraquín,Golmayo y Villaciervos,SO,12000,GAMESA,6,2000,0.425287