# Ejercicio propuesto

- A partir del fichero CSV que se te proporciona, crea un programa llamado LabelEncoding.py que codifique las siguientes columnas:
  - Las columnas "cholesterol" y "gluc" miden el nivel de colesterol y glucosa de los pacientes. Sus valores son "Normal", "Above Normal" y "Well Above Normal", y queremos codificarlos como 0, 1 y 2 respectivamente.
  - Las columnas "smoke", "alco", "active" y "cardio" indican si el paciente fuma, bebe alcohol, tiene una vida activa o si tiene problemas cardíacos, respectivamente. Queremos codificarlos como 0 (No) o 1 (Sí).
  - Reemplaza directamente la columna original con los nuevos valores codificados, en cada caso.

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("datos_salud.csv", sep=',')
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,M,168,62.0,110,80,Normal,Normal,No,No,Yes,No
1,1,55,F,156,85.0,140,90,Well Above Normal,Normal,No,No,Yes,Yes
2,2,51,F,165,64.0,130,70,Well Above Normal,Normal,No,No,No,Yes
3,3,48,M,169,82.0,150,100,Normal,Normal,No,No,Yes,Yes
4,4,47,F,156,56.0,100,60,Normal,Normal,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,52,M,168,76.0,120,80,Normal,Normal,Yes,No,Yes,No
69996,99995,61,F,158,126.0,140,90,Above Normal,Above Normal,No,No,Yes,Yes
69997,99996,52,M,183,105.0,180,90,Well Above Normal,Normal,No,Yes,No,Yes
69998,99998,61,F,163,72.0,135,80,Normal,Above Normal,No,No,No,Yes
69999,99999,56,F,170,72.0,120,80,Above Normal,Normal,No,No,Yes,No

In [15]:
scores_dict = {'Normal':0, 'Above Normal': 1, 'Well Above Normal': 2}
df['cholesterol'] = df['cholesterol'].map(scores_dict)
df['gluc'] = df['gluc'].map(scores_dict)
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,M,168,62.0,110,80,0,0,No,No,Yes,No
1,1,55,F,156,85.0,140,90,2,0,No,No,Yes,Yes
2,2,51,F,165,64.0,130,70,2,0,No,No,No,Yes
3,3,48,M,169,82.0,150,100,0,0,No,No,Yes,Yes
4,4,47,F,156,56.0,100,60,0,0,No,No,No,No

In [16]:
yes_no_dict = {'No': 0, 'Yes': 1}
df["smoke"] = df["smoke"].map(yes_no_dict)
df["alco"] = df["alco"].map(yes_no_dict)
df["active"] = df["active"].map(yes_no_dict)
df["cardio"] = df["cardio"].map(yes_no_dict)
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,M,168,62.0,110,80,0,0,0,0,1,0
1,1,55,F,156,85.0,140,90,2,0,0,0,1,1
2,2,51,F,165,64.0,130,70,2,0,0,0,0,1
3,3,48,M,169,82.0,150,100,0,0,0,0,1,1
4,4,47,F,156,56.0,100,60,0,0,0,0,0,0