# Ejercicio propuesto

Crea un programa CalculosEstadisticos.py y, partiendo del CSV que se proporciona:

In [52]:
import pandas as pd
import numpy as np
from scipy.stats import skew

In [53]:
df = pd.read_csv("players.csv", sep=',')
df.head()

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds
0,14,Ike,NaN,NaN,Anigbogu,C,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
1,25,Ron,NaN,NaN,Baker,G,"{'id': 20, 'abbreviation': 'NYK', 'city': 'New...",NaN
2,47,Jabari,NaN,NaN,Bird,G,"{'id': 2, 'abbreviation': 'BOS', 'city': 'Bost...",NaN
3,67,MarShon,NaN,NaN,Brooks,G,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
4,71,Lorenzo,NaN,NaN,Brown,G,"{'id': 28, 'abbreviation': 'TOR', 'city': 'Tor...",NaN

- Elimina las filas que tengan valores nulos (calcula cuántas son).

In [54]:
# Contar totalidad de filas antes de eliminar NaNs
filas_iniciales = len(df)
print(f"Cantidad de filas antes de la criba: {filas_iniciales}")

Cantidad de filas antes de la criba: 5130

In [55]:
# Eliminar filas con al menos un valor nulo
df = df.dropna()

In [56]:
# Contar totalidad de filas después de eliminar NaNs
filas_finales = len(df)
print(f"Cantidad de filas después de la criba: {filas_finales}")

Cantidad de filas después de la criba: 457

In [57]:
# Cantidad de filas eliminadas
filas_eliminadas = filas_iniciales - filas_finales
print(f"Filas eliminadas: {filas_eliminadas}")

Filas eliminadas: 4673

- Convierte la altura en pies (feet) en centímetros (1 pie = 30.48 cm.) en una nueva columna `height_cm`.

In [58]:
df['height_cm'] = df['height_feet'] * 30.48
df.head()

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds,height_cm
6,1,Alex,6.0,6.0,Abrines,G,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",200.0,182.88
11,241,Amir,6.0,9.0,Johnson,C-F,"{'id': 23, 'abbreviation': 'PHI', 'city': 'Phi...",240.0,182.88
14,263,Kosta,7.0,0.0,Koufos,C,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",245.0,213.36
2570,39,Michael,6.0,9.0,Beasley,F,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",235.0,182.88
2571,245,Wesley,6.0,7.0,Johnson,F-G,"{'id': 30, 'abbreviation': 'WAS', 'city': 'Was...",215.0,182.88

- Convierte el peso en libras (pounds) en Kg (1 libra = 0.45 Kg) en una nueva columna `weight_kg`.

In [59]:
df['weight_kg'] = (df['weight_pounds'] * 0.45).round(2)
df.head()

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds,height_cm,weight_kg
6,1,Alex,6.0,6.0,Abrines,G,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",200.0,182.88,90.00
11,241,Amir,6.0,9.0,Johnson,C-F,"{'id': 23, 'abbreviation': 'PHI', 'city': 'Phi...",240.0,182.88,108.00
14,263,Kosta,7.0,0.0,Koufos,C,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",245.0,213.36,110.25
2570,39,Michael,6.0,9.0,Beasley,F,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",235.0,182.88,105.75
2571,245,Wesley,6.0,7.0,Johnson,F-G,"{'id': 30, 'abbreviation': 'WAS', 'city': 'Was...",215.0,182.88,96.75

- Elimina las columnas `id`, `height_feet`, `height_inches` y `weight_pounds`.

In [60]:
df = df.drop('id', axis=1)
df = df.drop('height_feet', axis=1)
df = df.drop('height_inches', axis=1)
df = df.drop('weight_pounds', axis=1)
df

,first_name,last_name,position,team,height_cm,weight_kg
6,Alex,Abrines,G,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",182.88,90.00
11,Amir,Johnson,C-F,"{'id': 23, 'abbreviation': 'PHI', 'city': 'Phi...",182.88,108.00
14,Kosta,Koufos,C,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",213.36,110.25
2570,Michael,Beasley,F,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",182.88,105.75
2571,Wesley,Johnson,F-G,"{'id': 30, 'abbreviation': 'WAS', 'city': 'Was...",182.88,96.75
...,...,...,...,...,...,...
5017,Mitchell,Robinson,C,"{'id': 20, 'abbreviation': 'NYK', 'city': 'New...",213.36,108.00
5026,Collin,Sexton,G,"{'id': 29, 'abbreviation': 'UTA', 'city': 'Uta...",182.88,85.50
5027,Landry,Shamet,G,"{'id': 24, 'abbreviation': 'PHX', 'city': 'Pho...",182.88,84.60
5028,Anfernee,Simons,G,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",182.88,83.25
5030,Jarred,Vanderbilt,F,"{'id': 14, 'abbreviation': 'LAL', 'city': 'Los...",182.88,96.30

- Averigua quién es el jugador más alto y el de menos peso.

In [61]:
#jugador_mas_alto = df['height_cm'].max()
jugador_mas_alto = df.loc[df['height_cm'].idxmax()]
print(f"Jugador más alto:\n{jugador_mas_alto}")

Jugador más alto:
first_name                                                Kosta
last_name                                                Koufos
position                                                      C
team          {'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...
height_cm                                                213.36
weight_kg                                                110.25
Name: 14, dtype: object

In [62]:
#jugador_menor_peso = df['weight_kg'].min()
jugador_menor_peso = df.loc[df['weight_kg'].idxmin()]
print(f"Jugador menor peso:\n{jugador_menor_peso}")

Jugador menor peso:
first_name                                                  Tim
last_name                                               Frazier
position                                                      G
team          {'id': 6, 'abbreviation': 'CLE', 'city': 'Clev...
height_cm                                                182.88
weight_kg                                                  76.5
Name: 3201, dtype: object

- Calcula la media, la mediana y la asimetría de las alturas e indica de qué tipo es dicha asimetría.

In [65]:
media_altura = df['height_cm'].mean()
mediana_altura = df['height_cm'].median()
asimetria_altura = skew(df['height_cm'])
print(f"Media: {media_altura:.3f}")
print(f"Mediana: {mediana_altura:.3f}")
print(f"Asimetría: {asimetria_altura:.3f}")

Media: 185.615
Mediana: 182.880
Asimetría: 2.378